import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtemp,readFile,writeFile,readdir} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {spawn} from 'node:child_process';
import net from 'node:net';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
const root=path.dirname(path.dirname(fileURLToPath(import.meta.url)));
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
async function until(fn){const end=Date.now()+7000;let last;while(Date.now()<end){try{const v=await fn();if(v)return v;}catch(e){last=e;}await sleep(50);}throw last||new Error('Test condition timed out');}
test('full panel workflow preserves scoped bindings, blocks conflicts and releases capture',{timeout:40000},async t=>{
  const dir=await mkdtemp(path.join(process.env.MICRO_TEST_ROOT||tmpdir(),'micro-windows-test-'));
  const socket=net.createServer();await new Promise(r=>socket.listen(0,'127.0.0.1',r));const port=socket.address().port;await new Promise(r=>socket.close(r));
  const origin=`http://127.0.0.1:${port}`,fixture=path.join(dir,'fixture.json'),commands=path.join(dir,'commands.jsonl');let spec={sequence:0,autoTap:true};
  await writeFile(fixture,JSON.stringify(spec));
  let output='';const child=spawn(process.execPath,[path.join(root,'server.mjs')],{cwd:root,windowsHide:true,env:{...process.env,MICRO_WINDOWS_DATA:dir,MICRO_WINDOWS_PORT:String(port),MICRO_WINDOWS_TEST:'1',MICRO_WINDOWS_HELPER:path.join(root,'tests/mock-hid.mjs'),MICRO_WINDOWS_FIXTURE:fixture,MICRO_WINDOWS_COMMANDS:commands},stdio:['ignore','pipe','pipe']});
  child.stdout.on('data',b=>output+=b);child.stderr.on('data',b=>output+=b);
  const post=async(route,body={},expected=200)=>{const r=await fetch(origin+route,{method:'POST',headers:{Origin:origin,'Content-Type':'application/json','X-Micro-Panel':'1'},body:JSON.stringify(body)});const value=await r.json();assert.equal(r.status,expected,JSON.stringify(value)+' '+output);return value;};
  const state=async()=>{const r=await fetch(origin+'/api/state');return r.json();};
  const change=async patch=>{spec={...spec,...patch,sequence:spec.sequence+1};await writeFile(fixture,JSON.stringify(spec));await sleep(100);};
  const history=async()=>(await readFile(commands,'utf8')).trim().split('\n').map(JSON.parse);
  t.after(async()=>{if(child.exitCode===null){try{await post('/api/quit');}catch{child.kill();}}await until(()=>child.exitCode!==null).catch(()=>child.kill());});
  await until(async()=>{const s=await state();return s.status.ready;});
  assert.equal((await state()).status.simulation,true);
  const rejected=await fetch(origin+'/api/vendor-enabled',{method:'POST',headers:{'Content-Type':'application/json'},body:'{"enabled":true}'});assert.equal(rejected.status,403);
  assert.equal((await fetch(origin+'/../server.mjs')).status,404);
  await post('/api/learn',{controlId:'key1'});await until(async()=>Boolean((await state()).bindings.key1));
  let s=await state();assert.equal(s.bindings.key1.source.code,'AG00');assert.equal(s.status.enabled,false);assert.equal(s.status.captured,false);
  await post('/api/save',{controlId:'key1',action:'copy'});
  await until(async()=>(await history()).filter(c=>c.op==='key').length>=2);
  let emitted=(await history()).filter(c=>c.op==='key');assert.deepEqual(emitted.slice(-2).map(c=>[c.code,c.modifiers,c.down]),[[67,[162],true],[67,[162],false]]);
  await post('/api/learn',{controlId:'key2'});s=await until(async()=>{const s=await state();return s.latestLearn?.controlId==='key2'?s:false;});
  assert.deepEqual(s.latestLearn.conflicts,['key1']);assert.equal(s.bindings.key2,undefined);
  await post('/api/share-source',{controlId:'key2',sessionId:s.latestLearn.sessionId});
  await post('/api/save',{controlId:'key1',action:'paste',sharedControlIds:[]},400);
  await post('/api/save',{controlId:'key1',action:'paste',sharedControlIds:['key1','key2']});
  s=await state();assert.equal(s.bindings.key1.action,'paste');assert.equal(s.bindings.key2.action,'paste');
  await post('/api/vendor-enabled',{enabled:false});await sleep(200);s=await state();assert.equal(s.status.enabled,false);assert.equal(s.status.captured,false);
  const captureCommands=(await history()).filter(c=>c.op==='capture');assert.equal(captureCommands.at(-1).value,false,'disable must not auto-resume via status callback');
  await change({deny:true,autoTap:false});await post('/api/vendor-enabled',{enabled:true},400);assert.equal((await state()).status.enabled,false);await sleep(100);assert.match((await state()).status.error,/占用/);
  await change({deny:false,device:'fixture-2'});s=await until(async()=>{const s=await state();return s.status.mismatch?s:false;});assert.equal(s.status.ready,false);
  await post('/api/save',{controlId:'key1',action:'copy',sharedControlIds:['key1','key2']},400);
  await post('/api/confirm-device');s=await state();assert.equal(s.status.mismatch,false);assert.equal(s.status.enabled,false);assert.equal(s.bindings.key1.action,'paste');
  await post('/api/learn',{controlId:'dial_cw'});s=await state();await post('/api/cancel-learn',{sessionId:'wrong-session'});assert.ok((await state()).learning);
  await post('/api/cancel-learn',{sessionId:s.learning.sessionId});assert.equal((await state()).learning,null);
  await post('/api/vendor-enabled',{enabled:true});await change({tap:true,act:1});await sleep(100);await change({connected:false,tap:false});
  await until(async()=>!(await state()).status.connected);assert.equal((await history()).at(-1).op,'release');
  const saved=JSON.parse(await readFile(path.join(dir,'bindings.json'),'utf8'));assert.equal(saved.bindings.key1.action,'paste');assert.equal(saved.device.location_id,'fixture-2');
  assert.ok((await readdir(path.join(dir,'backups'))).length>0);
  await post('/api/quit');await until(()=>child.exitCode!==null);assert.equal(child.exitCode,0,output);
});
